services:
  backend:
    image: "${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}"
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile 
      args:
        BACKEND_APP_MODULE: ${BACKEND_APP_MODULE-app.main:app}
        BACKEND_PRE_START_PATH: ${BACKEND_PRE_START_PATH-/app/prestart.sh}
        BACKEND_WITH_RELOAD: ${BACKEND_WITH_RELOAD-false}
        INSTALL_DEV: ${INSTALL_DEV-false}
