version: '3.8'

services:
  web:
    build: ./server
    command: uvicorn api:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./server:/usr/src/app
    ports:
      - 8004:8000
    depends_on:
      - web-db
  web-db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
